apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "ocha-demo"
spec:
  predictor:
    serviceAccountName: sa
    tensorflow:
      storageUri: "s3://census-income/serving_model"